version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: #remplir avec DB_PASSWORD
      POSTGRES_USER: #remplir avec DB_USERNAME
      POSTGRES_DB: #remplir avec DB_NAME
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: #choisir un email par exemple email@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: #choisir un mot de passe
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
