# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PG_PASS: ${{ secrets.PG_PASS }}
      DATABASE_URL: postgresql://postgres:${{ secrets.SECRET_PASSWORD }}@postgres/postgres
      PORT: 8000
  
    steps:
    - uses: actions/checkout@v4

    - name : Launch containers
      run: docker-compose up
      working-directory: ./server

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name : Install dependencies
      run: npm ci
      working-directory: ./server

    - name : Build
      run: npm run build --if-present
      working-directory: ./server


    - name : Run tests
      run: npm test
      working-directory: ./server
